### PR TITLE
timer

### LINKED ISSUE #79: timer
## Checks 
- [x] Project uses HTML , CSS , JS
- [x] Project can be hosted on GitHub 

## **Describe the Project**
Simple timer using Html, Css and js

### PR DESCRIPTION
**Pull request by nisha331**
# Description
This webapp is Timer to count time left for new year

Fixes #79   

## Type of change

- [x] New Project / Docs 
# Explain the Testing instructions

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK 

 https://nisha331.github.io/timer/

apture

### CODE REVIEW

**Review by Sanskriti2401 — CHANGES_REQUESTED** [review]
@nisha331 Remove unnecessary files other than timer.

**Comment by nisha331** [comment]
Only the html,css and js is there i belive. @Sanskriti2401 . What else do u see?

**Comment by nisha331** [comment]
hey, @Sanskriti2401 i found the unnessary files, can i just close the pr and create a new one. though the contribution period is over?

**Comment by Sanskriti2401** [comment]
Ya, do it asap!

**Pull request closed without merging**
