### PR TITLE
Snake Game

### LINKED ISSUE #42: Snake Game
## Checks 
[x] Project uses HTML , CSS , JS
[x] Project can be hosted on GitHub 

## **Describe the Project**

- Add a snake game

## **Screenshots**

- If applicable, add screenshots to help explain your project.

### PR DESCRIPTION
**Pull request by Atif0604**
# Description

Added Snake Game
Fixes #42 
Snake Game 

## Type of change

- [x] New Project / Docs 

# Explain the Testing instructions

**Test Configuration**:
* Operating system:
* Version:
* Text-editors used:
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK 
preview

### CODE REVIEW

**Comment by Atif0604** [comment]
hey @Sanskriti2401 
please review my pr

**Comment by Sanskriti2401** [comment]
@Atif0604 Can you deploy it with github page?

**Comment by Atif0604** [comment]
> @Atif0604 Can you deploy it with github page?

Yes it can be deployed on github page @Sanskriti2401

**Comment by Sanskriti2401** [comment]
Kindly deploy it and share the link in the readme.

**Comment by Atif0604** [comment]
Done @Sanskriti2401

**Comment by Sanskriti2401** [comment]
Great work @Atif0604

**Pull request merged**
