### PR TITLE
Media query

### LINKED ISSUE #78: Media Queries- CSS Docs
## Which Topic Notes will you like to add 

- [x] CSS

## **Describe the Topic **
Media Queries in CSS

### PR DESCRIPTION
**Pull request by gunjan-g**
# Description
Notes for media query in CSS

Fixes #78 

## Type of change
- [x] New Project / Docs 

# Explain the Testing instructions
 
# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK 
image

### CODE REVIEW

**Comment by gunjan-g** [comment]
@Sanskriti2401 please review the pr

**Comment by gunjan-g** [comment]
@Sanskriti2401 please review the pr

**Comment by gunjan-g** [comment]
@Sanskriti2401 please review the pr under LGMSOC

**Comment by gunjan-g** [comment]
@Sanskriti2401 please review the pr under LGMSOC

**Review by Sanskriti2401 — APPROVED** [review]

**Pull request merged**
