### PR TITLE
Added Coin Toss App

### LINKED ISSUE #68: Coin Toss App
## Checks 
[x] Project uses HTML , CSS , JS
[x] Project can be hosted on GitHub 

## **Describe the Project**

This app will simulates a coin flip which will produce head and tails with a cool animation. It also maintains the count of heads and tails. We can also reset the count of heads and tails using reset button.

## **Screenshots**

- If applicable, add screenshots to help explain your project.

### PR DESCRIPTION
**Pull request by khushi-purwar**
# Description

This app will simulates a coin flip which will produce head and tails with a cool animation. It also maintains the count of heads and tails. We can also reset the count of heads and tails using reset button.

Fixes #68

## Type of change

- [x] New Project / Docs 

# Explain the Testing instructions

**Test Configuration**:
* Operating system:
* Version:
* Text-editors used:
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK 
ss1

Deployment Link:
https://khushi-purwar.github.io/WebDev-Playyard/Projects/Coin%20Toss%20App/

### CODE REVIEW

**Comment by Sanskriti2401** [comment]
@khushi-purwar Kindly provide valid deployment link

**Comment by khushi-purwar** [comment]
> @khushi-purwar Kindly provide valid deployment link

https://khushi-purwar.github.io/WebDev-Playyard/Projects/Coin%20Toss%20App/

**Comment by khushi-purwar** [comment]
Two my PR's did not get tag, please provide tag for them also. #22 and #53

**Comment by Sanskriti2401** [comment]
> Two my PR's did not get tag, please provide tag for them also. #22 and #53

Done and thanks for informing us.

**Review by Sanskriti2401 — APPROVED** [review]

**Comment by khushi-purwar** [comment]
> > Two my PR's did not get tag, please provide tag for them also. #22 and #53
> 
> Done and thanks for informing us.

😊

**Pull request merged**
