### PR TITLE
Weather-App

### LINKED ISSUE #34: Weather App
## Checks 
[x] Project uses HTML , CSS , JS
[x] Project can be hosted on GitHub 

## **Describe the Project**

- Weather App using open weather api

## **Screenshots**

- If applicable, add screenshots to help explain your project.

### PR DESCRIPTION
**Pull request by Atif0604**
# Description
Added Weather App using two Apis openweather and unsplash 

Fixes #34 
Weather App 

## Type of change

- [x] New Project / Docs 

# Explain the Testing instructions

**Test Configuration**:
* Operating system:
* Version:
* Text-editors used:
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK 
Weather-App

### CODE REVIEW

**Comment by Atif0604** [comment]
hey @Sanskriti2401 
Please Review my PR

**Comment by Sanskriti2401** [comment]
@Atif0604 your work is good but kindly follow the project structure .

**Comment by Sanskriti2401** [comment]
Screenshot 2021-07-30 124508

This is the project structure. Include js files in the script folder and in assets make two folders of media and CSS. Inside media include css files and in media include images used in project.

**Comment by Atif0604** [comment]
Hey @Sanskriti2401 is it good to go now?

**Comment by Sanskriti2401** [comment]
> Hey @Sanskriti2401 is it good to go now?

Ya, Great !!

**Pull request merged**
