### PR TITLE
TO DO LIST

### PR DESCRIPTION
**Pull request by jainapoorva40**
Description
Added a new project. A TO DO LIST app using html and javascript.

 (issue no.)
#38 

Type of change
 New Project .

Text-editors used: VS Code.

Checklist:
 My code follows the style guidelines of this project
 I have performed a self-review of my own code
 My changes generate no new warnings
 
ATTACH SCREEN-SHOTS / DEPLOYMENT LINK:

Screenshot (670)

https://jainapoorva40.github.io/To-do-list/

### CODE REVIEW

**Comment by Sanskriti2401** [comment]
@jainapoorva40 Aline the dustbin symbol with text ( When the task is added in the list) and if possible add the functionality that once we type any task and add it, then it will automatically clear what's written in the text input.

**Comment by Sanskriti2401** [comment]
Let me know if you didn't understand the changes.

**Review by Sanskriti2401 — CHANGES_REQUESTED** [review]
Let me know if you didn't understand the changes.

**Comment by jainapoorva40** [comment]
Thanks a lot ma'am for the review.
I will try best to carry out the changes suggested by you.

**Comment by jainapoorva40** [comment]
@Sanskriti2401 
I have made the suggested changes , would be great if you could review the pull request.

**Comment by Sanskriti2401** [comment]
@jainapoorva40 Great :)

**Comment by Sanskriti2401** [comment]
@jainapoorva40 the project should not be inside project structure folder , kindly move it outside.

**Comment by Sanskriti2401** [comment]
Screenshot 2021-08-01 184822

See this

**Comment by Sanskriti2401** [comment]
@jainapoorva40 Its good now.

**Review by Sanskriti2401 — APPROVED** [review]

**Pull request merged**
