### PR TITLE
lets practice

### LINKED ISSUE #70: Lets practice
## Checks 
[ ] Project uses HTML , CSS , JS
[ ] Project can be hosted on GitHub 

## **Describe the Project**
This webapp is basically for kids to practice addition, substraction, multiplication and division.
## **Screenshots**
pr
d

### PR DESCRIPTION
**Pull request by nisha331**
# Description
This webapp is basically for kids to practice addition, substraction, multiplication and division.

Fixes #70 

## Type of change

- [x] New Project / Docs 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK 

https://nisha331.github.io/lets-practice/

a
s
d

### CODE REVIEW

**Comment by rohan-kulkarni-25** [comment]
@Sanskriti2401 @SnehaAgarwal361  Have a look and please give a review

**Review by Sanskriti2401 — CHANGES_REQUESTED** [review]
@nisha331 
1. Correct the spelling of Subtraction. 
2. Move the readme inside the project file.
3. Move HTML file outside script
4. Give space after "is word(Its alert box of division)
5.  Screenshot 2021-08-07 223144

**Comment by nisha331** [comment]
@Sanskriti2401 is it fine now?

**Comment by Sanskriti2401** [comment]
@nisha331Kindly provide new deployment link.

**Comment by Sanskriti2401** [comment]
The old one is not reflecting the changes.

**Comment by nisha331** [comment]
@Sanskriti2401 its working now.

**Review by Sanskriti2401 — APPROVED** [review]

**Pull request merged**
