### PR TITLE
Tindog

### LINKED ISSUE #58: Tindog- Tinder for Dogs
## Checks 

- [x]  Project uses HTML , CSS , Bootstrap
- [x] Project can be hosted on GitHub 

## **Describe the Project**
This project is a beginner friendly project which uses HTML , CSS and Bootstrap to build up this entire beautiful website. This is a tinder website designed especially for dogs.

## **Screenshots**
image

### PR DESCRIPTION
**Pull request by gunjan-g**
# Description
Added Project in the specified folder and following the guidelines

Fixes #58 

## Type of change
- [x] New Project / Docs 

# Explain the Testing instructions

**Test Configuration**:
* Operating system: Windows 
* Version: 10
* Text-editors used: VS Code
 
# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK 
https://gunjan-g.github.io/TINDOG/

### CODE REVIEW

**Comment by gunjan-g** [comment]
@Sanskriti2401 please review the pr

**Comment by gunjan-g** [comment]
@Sanskriti2401 please review the pr

**Comment by gunjan-g** [comment]
@Sanskriti2401 please review the pr

**Comment by gunjan-g** [comment]
@Sanskriti2401 please review the pr

**Comment by Sanskriti2401** [comment]
@gunjan-g 
Screenshot 2021-08-04 160944
The logo is missing.

**Review by Sanskriti2401 — CHANGES_REQUESTED** [review]
Screenshot 2021-08-04 161010
Make all the cards of the same length and the color of the button should be same.

**Comment by gunjan-g** [comment]
@Sanskriti2401 made all the changes, please verify

**Review by Sanskriti2401 — APPROVED** [review]

**Comment by Sanskriti2401** [comment]
@gunjan-g Good work :)

**Pull request merged**
