### PR TITLE
Create table.md

### LINKED ISSUE #4: Html table tag.
## Which Topic Notes will you like to add 
[x] HTML
[ ] CSS
[ ] JS

## **Describe the Topic **
- I would like to add table tag in html

### PR DESCRIPTION
**Pull request by siddhi-244**
# Description
Added table tag in html notes.
Fixes #4 

## Type of change
- [x] New Project / Docs 

 
# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by rohan-kulkarni-25 — CHANGES_REQUESTED** [review]
Can you please add the preview image of the table at the bottom of the file so it will be easy for participants to guess the outcome

**Comment by siddhi-244** [comment]
> Can you please add the preview image of the table at the bottom of the file so it will be easy for participants to guess the outcome

Ok as soon as power comes. I will add that for sure. But rest all is fyn ?

**Comment by siddhi-244** [comment]
@rohan-kulkarni-25  Done !

**Review by rohan-kulkarni-25 — APPROVED** [review]
Great work  @SnehaAgarwal361  have a look over it LGTM 🚀

**Comment by siddhi-244** [comment]
You haven't added labels ! @rohan-kulkarni-25

**Review by SnehaAgarwal361 — COMMENTED** [review]
Code seems neat and correctly implemented.
Good job @siddhi-244 
Make sure from the next time to add some short vd if possible of your work!

**Comment by siddhi-244** [comment]
> Code seems neat and correctly implemented.
> Good job @siddhi-244
> Make sure from the next time to add soke short vd and screenshots of your work!

Sure !

**Pull request merged**
