### PR TITLE
added Memory card game

### LINKED ISSUE #14: Memory Card Game
## Checks 
[✔] Project uses HTML , CSS , JS
[✔] Project can be hosted on GitHub 

## **Describe the Project**

- A basic memory card game that tests user memory by remembering where the cards actually are.

## **Screenshots**

- Screenshots are there in the README.md of my project,

### PR DESCRIPTION
**Pull request by palaksinghania05**
# Description
A basic memory test game where the main trick is to remember where the cards actually are.

Fixes #14 

## Type of change
- [x] New Project / Docs 

# Explain the Testing instructions
**Test Configuration**:
* Operating system: Windows 10
* Text-editors used: VS Code
 
# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK 
- Included in the readme itself

### CODE REVIEW

**Comment by rohan-kulkarni-25** [comment]
@palaksinghania05  Can you please deploy project to github

**Comment by palaksinghania05** [comment]
@rohan-kulkarni-25 if I'm not mistaking then do you mean should I deploy it on Github pages and submit the link here?

**Comment by rohan-kulkarni-25** [comment]
Yes

**Comment by palaksinghania05** [comment]
I tried but it should only be done if it contains an index.html file that is not in my folder.

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> I tried but it should only be done if it contains an index.html file that is not in my folder.

you can make index.html file to your main file as this will help you always

**Comment by palaksinghania05** [comment]
@rohan-kulkarni-25 
I renamed it and here's the hosted site link: 
https://palaksinghania05.github.io/Memory-Card-Game/

**Pull request merged**
