### PR TITLE
Sudoku Solver

### LINKED ISSUE #13: Sudoku Solver
## Checks 
[x] Project uses HTML , CSS , JS
[x] Project can be hosted on GitHub 

## **Describe the Project**

- **Sudoku Solver**
WhatsApp Image 2021-07-21 at 22 41 36 (1)

The project is done using html ,javascript and css using the concept of backtracking

Stack:
[x] Html
[x] CSS
[x] JavaScript

## **Screenshots**

- If applicable, add screenshots to help explain your project.

### PR DESCRIPTION
**Pull request by soma2000-lang**
# Description

Added the files of Sudoku Solver made using  html,css and js
Fixes #13

## Type of change

- [x] New Project / Docs 

# Explain the Testing instructions

**Test Configuration**:
* Operating system:Windows

* Text-editors used:Vs code
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
## The project can be hosted in github pages via https://soma2000-lang.github.io/Sudoku-Solver/
WhatsApp Image 2021-07-21 at 22 41 36 (1)

### CODE REVIEW

**Comment by soma2000-lang** [comment]
@rohan-kulkarni-25 @SnehaAgarwal361  kindly check

**Comment by SnehaAgarwal361** [comment]
The interface is working perfectly fine.
Good job!

**Comment by soma2000-lang** [comment]
@SnehaAgarwal361 @rohan-kulkarni-25  can you please tag this issue like level 1,2 ,3 or 4

**Comment by SnehaAgarwal361** [comment]
Done!

**Pull request merged**
