### PR TITLE
Project Addition-The Dice Game 

### LINKED ISSUE #65: The Dice Game
## Checks 
[  :heavy_check_mark: ] Project uses HTML , CSS , JS
[  :heavy_check_mark: ] Project can be hosted on GitHub 

## **Describe the Project**

- It is a simple website created using HTML,CSS and Javascript. Here, user can play a dice game and the dices shown on the page will show a different number each time, and the player with larger number will win. The result will be shown above. 

## **Screenshots**

Untitled (3)

### PR DESCRIPTION
**Pull request by Ruheej1**
# Description

It is a simple website created using HTML,CSS and Javascript. Here, user can play a dice game and the dices shown on the page will show a random number each time, and the player with larger number will win. The result will be shown above.

Fixes #65 

## Type of change

- [x] New Project / Docs 

# Explain the Testing instructions

**Test Configuration**:
* Operating system: Windows
* Version: 10
* Text-editors used: Atom
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
 
 https://ruheej1.github.io/WebDev-Playyard/Projects/The%20Dice%20Game/

Untitled (3)

### CODE REVIEW

**Review by Sanskriti2401 — CHANGES_REQUESTED** [review]
@Ruheej1 Make a folder script and move js file into it. Also kindly share the valid deployment link.

**Comment by Sanskriti2401** [comment]
@Ruheej1 valid deployment link?

**Comment by Ruheej1** [comment]
I have moved the js file to the scripts folder, and I am trying to fix the deployment link.. It was working when I put it in readme..

**Comment by Sanskriti2401** [comment]
Okay fix it and update the readme. Just let me know when you are done, I will review it ASAP.

**Comment by Ruheej1** [comment]
> Okay fix it and update the readme. Just let me know you are done, I will review it ASAP.

Yes Done! Its working..the same link is working so readme need not be edited..

**Review by Sanskriti2401 — APPROVED** [review]
Great!!

**Pull request merged**
