### PR TITLE
Added Tip calculator

### LINKED ISSUE #48: Tip Calculator
## Checks 
- [x] Project uses HTML , CSS , JS
- [x] Project can be hosted on GitHub 

## **Describe the Project**

A tip calculator is a calculator that calculates a tip based on the total bill.

## **Screenshots**

- If applicable, add screenshots to help explain your project.

### PR DESCRIPTION
**Pull request by khushi-purwar**
# Description
A simple website build using HTML, CSS & JavaScript to calculate the tip amount for the bill.

Fixes #48 

## Type of change

- [x] New Project / Docs 

# Explain the Testing instructions

**Test Configuration**:
* Operating system:
* Version:
* Text-editors used:
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK 

ss1

Deployment link : 
https://khushi-purwar.github.io/WebDev-Playyard/Projects/Tip%20Calculator/

### CODE REVIEW

**Comment by SnehaAgarwal361** [comment]
The project seems to be smooth and the code is indeed clean, @Sanskriti2401 @ujju20 please review it once and give your suggestions.

**Review by ujju20 — COMMENTED** [review]
I agree with @SnehaAgarwal361 The code is clean and the site looks simple and cool.

**Review by Sanskriti2401 — CHANGES_REQUESTED** [review]
@khushi-purwar Please check the working ,there is some calculation error.
Screenshot 2021-08-02 002941

See the correct answer will be Rs. 900

**Comment by khushi-purwar** [comment]
Updated my js file. Now the output is right.

image

**Comment by Sanskriti2401** [comment]
Ya, looks good to me. @SnehaAgarwal361 @ujju20 We can merge it now.

**Review by Sanskriti2401 — APPROVED** [review]

**Pull request merged**
