### PR TITLE
timer

### LINKED ISSUE #79: timer
## Checks 
- [x] Project uses HTML , CSS , JS
- [x] Project can be hosted on GitHub 

## **Describe the Project**
Simple timer using Html, Css and js

### PR DESCRIPTION
**Pull request by nisha331**
# Description
Timer that counts the time left for the comming new year

Fixes #79 

## Type of change

- [x] New Project / Docs 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK 

 https://nisha331.github.io/timer/

apture

### CODE REVIEW

**Comment by nisha331** [comment]
@Sanskriti2401 hope this is fine.

**Comment by Sanskriti2401** [comment]
@nisha331 move js file inside script folder :(

**Comment by nisha331** [comment]
Done check it @Sanskriti2401 .. you must be fade up of me after merging so many project with similar mistakes.  :/

**Review by Sanskriti2401 — APPROVED** [review]

**Comment by Sanskriti2401** [comment]
> Done check it @Sanskriti2401 .. you must be fade up of me after merging so many project with similar mistakes. :/

Haha sometimes :)

**Pull request merged**
