### PR TITLE
Added Iframe tag under documentation

### LINKED ISSUE #29: iframe tag in HTML
## Which Topic Notes will you like to add 
[X] HTML
[ ] CSS
[ ] JS

## **Describe the Topic **
- A clear and concise description of what the topic is.
I would like to add notes for iframe tag .

### PR DESCRIPTION
**Pull request by Baba-Yaga-1**
I have added the iframe tag document. Can you check the PR ?

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue no.) 
Resolved #29 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New Project / Docs 
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:
* Operating system:
* Version:
* Text-editors used: 
 
# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by rohan-kulkarni-25 — APPROVED** [review]
LGTM 🥳 @Sanskriti2401 @SnehaAgarwal361

**Comment by SnehaAgarwal361** [comment]
The changes seems correctand neat to me.
Kindly review @ujju20 @Sanskriti2401

**Comment by rohan-kulkarni-25** [comment]
Merge it 👍🏻

**Comment by Sanskriti2401** [comment]
> The changes seems correctand neat to me.
> Kindly review @ujju20 @Sanskriti2401

Good to go from my side.

**Pull request merged**
