### PR TITLE
Contribution Guidelines

### LINKED ISSUE #5: Contribution guidelines
Hi I would to add Contribution guidelines in the folder . Please assign this to me

### PR DESCRIPTION
**Pull request by swathi-469**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #5 

Guidelines to be followed in Open-Source for the beginners are instructed step by step

- [x] New Project / Docs 
- [x] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:
* Operating system:
* Version:
* Text-editors used:
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules
# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by rohan-kulkarni-25** [comment]
@swathi-469  Please link issue to PR

**Comment by rohan-kulkarni-25** [comment]
@SnehaAgarwal361 @Sanskriti2401 @ujju20  Please give a read and if any changes required let @swathi-469  know about it please

**Comment by Sanskriti2401** [comment]
@swathi-469 In the first point of Relevant Screenshots/Gifs section, there is grammatical error in "Please merge me this PR". 
Make it "Please merge this PR" .

**Review by ujju20 — CHANGES_REQUESTED** [review]
@swathi-469 In the very first line you have written "We want to make contributing to this project.." change it to "We want to make contributions to this project..."

**Review by Sanskriti2401 — CHANGES_REQUESTED** [review]
In the first point of Relevant Screenshots/Gifs section, there is grammatical error in "Please merge me this PR". Make it "Please merge this PR" .

**Comment by swathi-469** [comment]
I have changed the grammatical errors and along with the required changes .... shall I wait for the other reviewer to review or else shall I make my pull request .... Please do let me know.

**Comment by ujju20** [comment]
> I have changed the grammatical errors and along with the required changes .... shall I wait for the other reviewer to review or else shall I make my pull request .... Please do let me know.

Why to make a new pull request you can commit your changes in this PR.

**Comment by swathi-469** [comment]
Yeah yeah I am sorry ... I have spelled wrongly so shall I wait for the another reviewer

**Comment by ujju20** [comment]
> Yeah yeah I am sorry ... I have spelled wrongly so shall I wait for the another reviewer

But You haven't committed yet 
commit your code so that we can check your code.

**Comment by swathi-469** [comment]
Yeah, I have committed now can you check it.

**Comment by ujju20** [comment]
> Yeah, I have committed now can you check it.

LGTM!
what say @Sanskriti2401 @SnehaAgarwal361

**Comment by Sanskriti2401** [comment]
Good to go from my side!  
@SnehaAgarwal361 give your review also.

**Comment by SnehaAgarwal361** [comment]
Yes now its fine!

**Review by SnehaAgarwal361 — COMMENTED** [review]
I guess we can merge!

**Pull request merged**
