### PR TITLE
Tabla

### LINKED ISSUE #51: tabla instrument
## Checks 
- [x] Project uses HTML , CSS , JS
- [x] Project can be hosted on GitHub 

## **Describe the Project**

A webapp that plays beats of tabla when clicked on it.

### PR DESCRIPTION
**Pull request by nisha331**
# Description
 webapp that plays the tabla beats 
Fixes #51 

## Type of change

- [x] New Project / Docs 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK 
https://nisha331.github.io/tabla/
Capture

### CODE REVIEW

**Comment by Sanskriti2401** [comment]
@nisha331 Kindly follow the project structure.
Screenshot 2021-08-02 003539

Refer this

**Comment by nisha331** [comment]
@Sanskriti2401 check if this works fine

**Comment by Sanskriti2401** [comment]
@nisha331 Move css file into assets->css-> (your css file) and all images inside assets->media->  (images)

**Comment by nisha331** [comment]
@Sanskriti2401 now?

**Review by Sanskriti2401 — CHANGES_REQUESTED** [review]
@nisha331 Remove extra read me file which is outside tabla and inside project folder. Rest is fine

**Review by Sanskriti2401 — APPROVED** [review]

**Comment by Sanskriti2401** [comment]
@nisha331 Great work !!

**Comment by nisha331** [comment]
Thanks finally !! haha.

**Pull request merged**
