### PR TITLE
Text to speech converter

### PR DESCRIPTION
**Pull request by nisha331**
# Description

Added a new project. A text to speech converter using js.

Fixes # (issue no.) 
#12 

## Type of change

- [x] New Project / Docs 

# Explain the Testing instructions

**Test Configuration**:

* Text-editors used: VS Code.
 
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK 

https://nisha331.github.io/text-to-speech-converter/

u

### CODE REVIEW

**Comment by Sanskriti2401** [comment]
@nisha331 Good Work ! but the project should not come inside project structure folder. Move it outside and create a folder naming your project name .

**Comment by Sanskriti2401** [comment]
Screenshot 2021-07-30 125457
Refer this ,rest is fine.

**Comment by nisha331** [comment]
@Sanskriti2401 is it fine now?

**Comment by Sanskriti2401** [comment]
@nisha331 No, html page is present in project structure folder, remove it from there. Readme should be inside your project name folder

**Comment by Sanskriti2401** [comment]
Please refer the project structure

**Comment by nisha331** [comment]
ok i am closing this pr and opening a new one.

**Pull request closed without merging**
